# PROJECT: Time Series Forcasting By using Recurrent Neural Network.

# Import  Important Libraries

In [1]:
import pandas as pd
import numpy as np

# Read Google Stock Price Dataset

In [2]:
A = pd.read_csv("C:/Users/JOHN/Downloads/Google_Stock_Price_Train.csv")
A 
# This Format is called OHLC format 
# O --> Opening price of the stock
# H --> Highest price of the stock
# L --> low price of the Stock
# C --> Closing price of the stock

Date    Open    High     Low   Close      Volume
0       1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1       1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2       1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3       1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4       1/9/2012  322.04  322.29  309.46  620.76  11,688,800
...          ...     ...     ...     ...     ...         ...
1253  12/23/2016  790.90  792.74  787.28  789.91     623,400
1254  12/27/2016  790.68  797.86  787.66  791.55     789,100
1255  12/28/2016  793.70  794.23  783.20  785.05   1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79     744,300
1257  12/30/2016  782.75  782.78  770.41  771.82   1,770,000

[1258 rows x 6 columns]

# Missing data Treatment

In [3]:
A.isna().sum() 

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [4]:
# No missing values in a dataset

# Get Stock Opening Price 

In [5]:
tr_data = A[["Open"]] 

In [6]:
tr_data

Open
0     325.25
1     331.27
2     329.83
3     328.34
4     322.04
...      ...
1253  790.90
1254  790.68
1255  793.70
1256  783.33
1257  782.75

[1258 rows x 1 columns]

# Scaling the data by MinMaxScaler

In [7]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
scaled_tr_data = mm.fit_transform(tr_data)
scaled_tr_data

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

# Create data for training  in such way that 50 rows as input and 51 row will be output

In [8]:
tr_data.head()

Open
0  325.25
1  331.27
2  329.83
3  328.34
4  322.04

In [9]:
tr_data.shape

(1258, 1)

In [10]:
xtrain = []
ytrain = []
for i in range(50,1258,1):
    xtrain.append(tr_data[i-50:i]) # 50 rows as input
    ytrain.append(tr_data[i:i+1]) # 51 row will be output

In [11]:
print(xtrain[0],"\n") 
print(ytrain[0])

      Open
0   325.25
1   331.27
2   329.83
3   328.34
4   322.04
5   313.70
6   310.59
7   314.43
8   311.96
9   314.81
10  312.14
11  319.30
12  294.16
13  291.91
14  292.07
15  287.68
16  284.92
17  284.32
18  287.95
19  290.41
20  291.38
21  291.34
22  294.23
23  296.39
24  302.44
25  303.18
26  304.87
27  302.81
28  304.11
29  304.63
30  305.32
31  300.28
32  301.36
33  300.81
34  304.84
35  302.37
36  302.54
37  302.16
38  303.86
39  308.14
40  309.97
41  309.84
42  309.06
43  302.89
44  303.39
45  303.88
46  302.84
47  298.88
48  303.24
49  306.35 

      Open
50  307.15


In [ ]:
# data prepared for trainning

In [12]:
type(xtrain)

list

In [13]:
xtr = np.array(xtrain)# Neural Network always treated data in the form of array
ytr = np.array(ytrain)

In [14]:
xtr

array([[[325.25],
        [331.27],
        [329.83],
        ...,
        [298.88],
        [303.24],
        [306.35]],

       [[331.27],
        [329.83],
        [328.34],
        ...,
        [303.24],
        [306.35],
        [307.15]],

       [[329.83],
        [328.34],
        [322.04],
        ...,
        [306.35],
        [307.15],
        [309.29]],

       ...,

       [[779.8 ],
        [787.85],
        [798.24],
        ...,
        [792.36],
        [790.9 ],
        [790.68]],

       [[787.85],
        [798.24],
        [803.3 ],
        ...,
        [790.9 ],
        [790.68],
        [793.7 ]],

       [[798.24],
        [803.3 ],
        [795.  ],
        ...,
        [790.68],
        [793.7 ],
        [783.33]]])

In [15]:
ytr

array([[[307.15]],

       [[309.29]],

       [[310.4 ]],

       ...,

       [[793.7 ]],

       [[783.33]],

       [[782.75]]])

In [16]:
xtr.shape

(1208, 50, 1)

In [17]:
ytr.shape

(1208, 1, 1)

# Create a Recurrent Neural Network Model

In [18]:
from keras.models import Sequential
from keras.layers import LSTM,Dense,Dropout
from keras.callbacks import EarlyStopping


In [19]:
es = EarlyStopping(patience=5,monitor = "loss")
nn = Sequential()
nn.add(LSTM(50,return_sequences = True,input_shape = (50,1)))
nn.add(Dense(100))
nn.add(Dense(1))
nn.compile(optimizer="adam",loss = "mean_squared_error")
nn.fit(xtr,ytr,epochs=10000,callbacks=es)

Epoch 1/10000
38/38 [==============================] - 4s 32ms/step - loss: 311000.6250
Epoch 2/10000
38/38 [==============================] - 1s 32ms/step - loss: 291215.4375
Epoch 3/10000
38/38 [==============================] - 1s 33ms/step - loss: 254540.3125
Epoch 4/10000
38/38 [==============================] - 1s 35ms/step - loss: 209550.1250
Epoch 5/10000
38/38 [==============================] - 1s 33ms/step - loss: 158937.1875
Epoch 6/10000
38/38 [==============================] - 1s 33ms/step - loss: 110510.0703
Epoch 7/10000
38/38 [==============================] - 1s 34ms/step - loss: 70418.9375
Epoch 8/10000
38/38 [==============================] - 1s 35ms/step - loss: 44531.7148
Epoch 9/10000
38/38 [==============================] - 1s 33ms/step - loss: 30815.0801
Epoch 10/10000
38/38 [==============================] - 1s 32ms/step - loss: 24408.3047
Epoch 11/10000
38/38 [==============================] - 1s 34ms/step - loss: 19835.8418
Epoch 12/10000
38/38 [=============

# Read Testing dataset

In [20]:
tsd = pd.read_csv("C:/Users/JOHN/Downloads/Google_Stock_Price_Test.csv")
tsd.head(7)

Date    Open    High     Low   Close     Volume
0   1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1   1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2   1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3   1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4   1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5  1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6  1/11/2017  805.00  808.15  801.37  807.91  1,065,900

# Missing data treatment

In [21]:
tsd.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [ ]:
# there is no missing data in testing set

In [67]:
tsd

Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

# Get Open Price for testing

In [22]:
tsd[["Open"]]

Open
0   778.81
1   788.36
2   786.08
3   795.26
4   806.40
5   807.86
6   805.00
7   807.14
8   807.48
9   807.08
10  805.81
11  805.12
12  806.91
13  807.25
14  822.30
15  829.62
16  837.81
17  834.71
18  814.66
19  796.86

In [23]:
tsd.shape

(20, 6)

# concat two columns 

In [24]:
Q = pd.concat([A,tsd])
Q.index = range(0,1278) 

In [25]:
Q[["Open"]]

Open
0     325.25
1     331.27
2     329.83
3     328.34
4     322.04
...      ...
1273  829.62
1274  837.81
1275  834.71
1276  814.66
1277  796.86

[1278 rows x 1 columns]

In [26]:
Q = Q[["Open"]].values # data in the form of an array

In [27]:
Q

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [834.71],
       [814.66],
       [796.86]])

In [28]:
xtest = []
for i in range(1258,1277,1):
    xtest.append(Q[i-50:i])

In [29]:
type(xtest)

list

In [30]:
type(xtr)

numpy.ndarray

In [31]:
# we will have to convert xtest into same type of xtr

In [32]:
xts = np.array(xtest)

In [33]:
xts

array([[[803.3 ],
        [795.  ],
        [804.9 ],
        [816.68],
        [806.34],
        [801.  ],
        [808.35],
        [795.47],
        [782.89],
        [778.2 ],
        [767.25],
        [750.66],
        [774.5 ],
        [783.4 ],
        [779.94],
        [791.17],
        [756.54],
        [755.6 ],
        [746.97],
        [755.2 ],
        [766.92],
        [771.37],
        [762.61],
        [772.63],
        [767.73],
        [764.26],
        [760.  ],
        [771.53],
        [770.07],
        [757.44],
        [744.59],
        [757.71],
        [764.73],
        [761.  ],
        [772.48],
        [780.  ],
        [785.04],
        [793.9 ],
        [797.4 ],
        [797.34],
        [800.4 ],
        [790.22],
        [796.76],
        [795.84],
        [792.36],
        [790.9 ],
        [790.68],
        [793.7 ],
        [783.33],
        [782.75]],

       [[795.  ],
        [804.9 ],
        [816.68],
        [806.34],
        [801.  ],
        

In [34]:
type(xts)

numpy.ndarray

In [35]:
xts.shape

(19, 50, 1)

In [36]:
tsd

Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

# Prediction

In [37]:
pred_data = nn.predict(xts)

In [38]:
pred_data

array([[[611.7007 ],
        [692.0161 ],
        [716.6562 ],
        [731.54895],
        [739.54346],
        [745.25397],
        [750.8436 ],
        [751.983  ],
        [751.8307 ],
        [752.2811 ],
        [750.8493 ],
        [747.3229 ],
        [753.11365],
        [755.146  ],
        [754.5792 ],
        [756.76276],
        [749.42896],
        [749.0326 ],
        [746.63904],
        [748.55383],
        [751.21155],
        [752.07465],
        [749.9401 ],
        [752.07324],
        [750.90344],
        [749.9458 ],
        [748.76996],
        [751.2976 ],
        [750.87836],
        [747.70404],
        [744.0111 ],
        [747.28235],
        [748.8539 ],
        [747.7661 ],
        [750.29236],
        [751.84406],
        [752.8093 ],
        [754.4632 ],
        [755.09436],
        [755.0825 ],
        [755.60315],
        [753.76764],
        [754.9058 ],
        [754.7188 ],
        [754.03436],
        [753.70337],
        [753.59753],
        [754.

# What will be the Open Price on 1/3/2017

In [44]:
pred_data[0][49][0]

751.8084

751.8084 will be the predicted Open price on 1/3/2017